@echo off
set MATLAB=C:\Program Files\MATLAB\R2023b
"%MATLAB%\bin\win64\gmake" -f rtwshared.mk  RSIM_SOLVER_SELECTION=1 PCMATLABROOT="C:\\Program Files\\MATLAB\\R2023b" RSIM_PARAMETER_LOADING=1 OPTS="-DNRT -DIS_SIM_TARGET -DTGTCONN -DRSIM_PARAMETER_LOADING -DRSIM_WITH_SL_SOLVER -DENABLE_SLEXEC_SSBRIDGE=1 -DON_TARGET_WAIT_FOR_START=0"
