%% EV Battery Cooling System
%
% This demo shows an Electric Vehicle (EV) battery cooling system. The 
% battery packs are located on top of a cold plate which consists
% of cooling channels to direct the cooling liquid flow below the battery 
% packs. The heat absorbed by the cooling liquid is transported to the 
% Heating-Cooling Unit. The Heating-Cooling Unit consists of three branches
% to switch operating modes to cool and heat the battery. The Heater 
% represents an electrical heater for fast heating of the batteries under 
% low temperature conditions. The Radiator uses air-cooling and/or heating 
% when the batteries are operated stably. The Refrigerant system is used 
% for cooling the overheated batteries. The refrigeration cycle is 
% represented by the amount of heat flow extracted from the cooling liquid. 
% The system is simulated under either FTP-75 drive cycle or fast charge 
% scenarios with different environment temperatures.
%
% Copyright 2018 The MathWorks, Inc.

%% Model

open_system('EVBatteryCoolingSystem')

set_param(find_system('EVBatteryCoolingSystem','FindAll', 'on','type','annotation','Tag','ModelFeatures'),'Interpreter','off')

%% Battery Subsystem

open_system('EVBatteryCoolingSystem/Battery', 'force')

%% Cold Plate Subsystem

open_system('EVBatteryCoolingSystem/Cold Plate', 'force')

%% Cooling Plate (Pack 1) Subsystem

open_system('EVBatteryCoolingSystem/Cold Plate/Cooling Plate (Pack 1)', 'force')

%% Heating-Cooling Unit Subsystem

open_system('EVBatteryCoolingSystem/Heating-Cooling Unit', 'force')

%% Refrigerant Subsystem

open_system('EVBatteryCoolingSystem/Heating-Cooling Unit/Refrigerant System', 'force')

%% Radiator Subsystem

open_system('EVBatteryCoolingSystem/Heating-Cooling Unit/Radiator', 'force')

%% Heater Subsystem

open_system('EVBatteryCoolingSystem/Heating-Cooling Unit/Heater', 'force')

%% Pump Controller

open_system('EVBatteryCoolingSystem/Controller', 'force')

%% Air Stream

open_system('EVBatteryCoolingSystem/Air Stream', 'force')

%% Environment

open_system('EVBatteryCoolingSystem/Environment', 'force')

%% Simulation Results from Scopes
%%
%
set_param('EVBatteryCoolingSystem/Scope', 'open', 'on');
sim('EVBatteryCoolingSystem');

%%

set_param('EVBatteryCoolingSystem/Scope', 'open', 'off')

%% Simulation Results from Simscape Logging
%%
%
% This figure shows the performance of series of four lithium-ion battery 
% packs. The data used for each cell is based on T. Huria, M. Ceraolo, J. 
% Gazzarri,R. Jackey. "High Fidelity Electrical Model with Thermal 
% Dependence for Characterization and Simulation of High Power Lithium 
% Battery Cells," IEEE International Electric Vehicle Conference, March 2012.
%

EVBatteryCoolingSystemPlot1Battery;

%%
%
% This figure shows the total heat flow rate generated by batteries, the 
% total heat flow into to the coolant and the total heat flow extracted from 
% the coolant, and the contribution of each cooling system.
%

EVBatteryCoolingSystemPlot2Heat;

%%
%
% This figure shows the mechanical energy input for the cooling system.
%

EVBatteryCoolingSystemPlot3Energy;

%%


