@echo off
set MATLAB=C:\Program Files\MATLAB\R2023b
"%MATLAB%\bin\win64\gmake" -f Balancing_Logic.mk  GENERATE_ASAP2=0 EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 TMW_EXTMODE_TESTING=0 OPTS="-DIS_SIM_TARGET -DMATLAB_MEX_FILE -DTID01EQ=0"
